"use client"

import { Suspense, useEffect, useState, type FormEvent } from "react"
import { useRouter } from "next/navigation"
import { Loader2, Lock, ShieldCheck } from "lucide-react"

import { useLocale } from "@/components/providers/locale-provider"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { createSupabaseBrowserClient } from "@/lib/supabase/client"

export default function Page() {
  return (
    <Suspense fallback={null}>
      <ResetForm />
    </Suspense>
  )
}

/**
 * Set a new password from a recovery link.
 *
 * Until this existed the clinic had no way back into an account: there was a
 * login form, a change-password card for someone already signed in, and
 * nothing in between. A practitioner who forgot his password had to have it
 * reset by whoever provisioned the account and sent to him — which is how a
 * clinic's records end up behind a secret two people know.
 *
 * A recovery link is one of two shapes depending on how it was issued, and
 * this page takes both: `?code=` from the PKCE flow the app's own "forgot your
 * password" uses, and a `#access_token=` fragment from a link generated by an
 * administrator. Either way the session it establishes is a recovery session —
 * good for exactly one thing, which is the form below.
 */

/** Matches the change-password card. Ten, because these accounts open charts. */
const MIN_LENGTH = 10

function ResetForm() {
  const { t } = useLocale()
  const router = useRouter()
  const [ready, setReady] = useState(false)
  const [next, setNext] = useState("")
  const [confirm, setConfirm] = useState("")
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    const supabase = createSupabaseBrowserClient()
    if (!supabase) {
      setError(t("login.error.notConfigured"))
      return
    }
    void (async () => {
      const url = new URL(window.location.href)
      const code = url.searchParams.get("code")
      /*
       * A recovery token verified here rather than by Supabase's own redirect.
       * That redirect only honours addresses on the project's allow list and
       * otherwise silently falls back to the Site URL, which sends the
       * practitioner somewhere that is not this app; verifying the token
       * ourselves takes the redirect out of the path entirely.
       */
      const tokenHash = url.searchParams.get("token_hash")
      // The fragment never reaches the server, which is why this runs here and
      // not in a route handler.
      const hash = new URLSearchParams(window.location.hash.replace(/^#/, ""))
      const accessToken = hash.get("access_token")
      const refreshToken = hash.get("refresh_token")

      if (tokenHash) {
        const { error: otpError } = await supabase.auth.verifyOtp({
          type: "recovery",
          token_hash: tokenHash,
        })
        if (otpError) {
          setError(t("reset.error.link"))
          return
        }
      } else if (code) {
        const { error: exchangeError } = await supabase.auth.exchangeCodeForSession(code)
        if (exchangeError) {
          setError(t("reset.error.link"))
          return
        }
      } else if (accessToken && refreshToken) {
        const { error: sessionError } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken,
        })
        if (sessionError) {
          setError(t("reset.error.link"))
          return
        }
      } else {
        // Already signed in is fine — the form still does its job.
        const { data } = await supabase.auth.getUser()
        if (!data.user) {
          setError(t("reset.error.link"))
          return
        }
      }

      // Clear the token out of the address bar before the page can be shared,
      // bookmarked or screenshotted with a live credential in it.
      window.history.replaceState(null, "", window.location.pathname)
      setReady(true)
    })()
  }, [t])

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    // Trimmed exactly as the login form trims, so a password set here is a
    // password that can be typed back in.
    const value = next.trim()
    if (value.length < MIN_LENGTH) {
      setError(t("password.error.tooShort", { n: MIN_LENGTH }))
      return
    }
    if (value !== confirm.trim()) {
      setError(t("password.error.mismatch"))
      return
    }
    const supabase = createSupabaseBrowserClient()
    if (!supabase) return
    setBusy(true)
    const { error: updateError } = await supabase.auth.updateUser({ password: value })
    if (updateError) {
      setBusy(false)
      setError(updateError.message)
      return
    }
    router.replace("/dashboard")
    router.refresh()
  }

  return (
    <main className="flex min-h-dvh items-center justify-center bg-slate-50 px-4">
      <div className="w-full max-w-sm rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="mb-5 flex items-center gap-2">
          <ShieldCheck className="size-5 text-sky-600" aria-hidden />
          <h1 className="text-lg font-semibold text-slate-900">{t("reset.title")}</h1>
        </div>

        {!ready && !error && (
          <p className="flex items-center gap-2 text-sm text-slate-500">
            <Loader2 className="size-4 animate-spin" aria-hidden />
            {t("reset.checking")}
          </p>
        )}

        {error && !ready && (
          <>
            <p className="text-sm text-rose-600">{error}</p>
            <Button type="button" className="mt-4 w-full" onClick={() => router.replace("/login")}>
              {t("reset.backToLogin")}
            </Button>
          </>
        )}

        {ready && (
          <form onSubmit={handleSubmit} className="space-y-3">
            <p className="text-sm text-slate-500">{t("reset.body", { n: MIN_LENGTH })}</p>
            <Input
              type="password"
              autoComplete="new-password"
              value={next}
              onChange={(e) => setNext(e.target.value)}
              placeholder={t("reset.newPassword")}
              aria-label={t("reset.newPassword")}
            />
            <Input
              type="password"
              autoComplete="new-password"
              value={confirm}
              onChange={(e) => setConfirm(e.target.value)}
              placeholder={t("reset.confirmPassword")}
              aria-label={t("reset.confirmPassword")}
            />
            {error && <p className="text-sm text-rose-600">{error}</p>}
            <Button type="submit" className="w-full" disabled={busy}>
              {busy ? (
                <Loader2 className="size-4 animate-spin" aria-hidden />
              ) : (
                <Lock className="size-4" aria-hidden />
              )}
              {t("reset.submit")}
            </Button>
          </form>
        )}
      </div>
    </main>
  )
}
